"""Учебный контент бота: слова, чэнъюй, факты, мини-словарь."""

WORDS = [
    {"zh": "你好",  "py": "nǐ hǎo",    "ru": "Привет", "uz": "Salom", "en": "Hello"},
    {"zh": "谢谢",  "py": "xiè xie",   "ru": "Спасибо", "uz": "Rahmat", "en": "Thank you"},
    {"zh": "朋友",  "py": "péng yǒu",  "ru": "Друг", "uz": "Do'st", "en": "Friend"},
    {"zh": "学习",  "py": "xué xí",    "ru": "Учиться", "uz": "O'qimoq", "en": "To study"},
    {"zh": "加油",  "py": "jiā yóu",   "ru": "Давай! Не сдавайся!", "uz": "Harakat qil!", "en": "Go for it!"},
    {"zh": "梦想",  "py": "mèng xiǎng","ru": "Мечта", "uz": "Orzu", "en": "Dream"},
    {"zh": "缘分",  "py": "yuán fèn",  "ru": "Судьба встречи", "uz": "Taqdir", "en": "Fateful connection"},
    {"zh": "努力",  "py": "nǔ lì",     "ru": "Усердно стараться", "uz": "Harakat qilmoq", "en": "To work hard"},
    {"zh": "委屈",  "py": "wěi qū",    "ru": "Несправедливая обида, которую носишь молча", "uz": "Ichda saqlangan nohaqlik", "en": "Silently endured injustice"},
    {"zh": "旅行",  "py": "lǚ xíng",   "ru": "Путешествие", "uz": "Sayohat", "en": "Travel"},
    {"zh": "热闹",  "py": "rè nao",    "ru": "Оживлённо, шумно и весело", "uz": "Gavjum va quvnoq", "en": "Lively, bustling"},
    {"zh": "面子",  "py": "miàn zi",   "ru": "Лицо, репутация в глазах других", "uz": "Obro'", "en": "Face, social reputation"},
    {"zh": "差不多", "py": "chà bu duō","ru": "Примерно, почти, сойдёт", "uz": "Taxminan", "en": "More or less"},
    {"zh": "习惯",  "py": "xí guàn",   "ru": "Привычка; привыкать", "uz": "Odat", "en": "Habit; to get used to"},
    {"zh": "认真",  "py": "rèn zhēn",  "ru": "Серьёзно, добросовестно", "uz": "Jiddiy", "en": "Earnest, conscientious"},
]

CHENGYU = [
    {"zh": "塞翁失马", "py": "sài wēng shī mǎ",
     "ru": "Старик потерял коня — кто знает, не к счастью ли. Неудача может обернуться удачей.",
     "uz": "Chol otini yo'qotdi — baxt emasmi, kim biladi. Omadsizlik baxtga aylanishi mumkin.",
     "en": "The old man lost his horse — who knows if it's a blessing. Misfortune may turn to luck.",
     "ex": "别灰心，塞翁失马，焉知非福。"},
    {"zh": "功夫不负有心人", "py": "gōng fu bù fù yǒu xīn rén",
     "ru": "Усилия не подведут того, кто вкладывает сердце.",
     "uz": "Mehnat chin dildan harakat qilganni aldamaydi.",
     "en": "Hard work never betrays those who put their heart in.",
     "ex": "只要坚持，功夫不负有心人。"},
    {"zh": "半途而废", "py": "bàn tú ér fèi",
     "ru": "Бросить на полпути, не доведя дело до конца.",
     "uz": "Ishni yarim yo'lda tashlab qo'yish.",
     "en": "To give up halfway.",
     "ex": "学语言最怕半途而废。"},
    {"zh": "对牛弹琴", "py": "duì niú tán qín",
     "ru": "Играть на цине перед быком — метать бисер перед тем, кто не поймёт.",
     "uz": "Ho'kiz oldida chang chalish — tushunmaydiganga gapirish.",
     "en": "Playing the lute to a cow — wasting words on someone who won't understand.",
     "ex": "跟他讲这些简直是对牛弹琴。"},
    {"zh": "画蛇添足", "py": "huà shé tiān zú",
     "ru": "Пририсовать змее ноги — переусердствовать и всё испортить.",
     "uz": "Ilonga oyoq chizish — ortiqcha harakat bilan ishni buzish.",
     "en": "Drawing legs on a snake — ruining something by overdoing it.",
     "ex": "别再改了，小心画蛇添足。"},
    {"zh": "一石二鸟", "py": "yī shí èr niǎo",
     "ru": "Одним камнем двух птиц — решить две задачи одним действием.",
     "uz": "Bir tosh bilan ikki qush.",
     "en": "Two birds with one stone.",
     "ex": "这个办法一石二鸟。"},
]

FACTS = [
    {"ru": "🔴 Красный в Китае — цвет счастья и защиты. Деньги дарят в красных конвертах 红包, и Новый год весь красный.",
     "uz": "🔴 Qizil rang Xitoyda baxt va himoya ramzi. Pul qizil konvertlarda (红包) sovg'a qilinadi.",
     "en": "🔴 Red means luck and protection in China. Money gifts go in red envelopes 红包.",
     "zh": "🔴 红色在中国象征幸福和保护。送礼金要装在红包里。"},
    {"ru": "4️⃣ Во многих зданиях нет четвёртого этажа: 四 (sì) звучит как 死 (sǐ) — смерть. Зато 八 (bā) похоже на 发 (fā) «богатеть», поэтому номера с восьмёрками стоят дороже.",
     "uz": "4️⃣ Ko'p binolarda 4-qavat yo'q: 四 (sì) 死 (sǐ) — o'lim kabi eshitiladi. 八 (bā) esa 发 (fā) — boyishga o'xshaydi.",
     "en": "4️⃣ Many buildings skip floor 4: 四 (sì) sounds like 死 (sǐ), death. But 八 (bā) echoes 发 (fā), to prosper.",
     "zh": "4️⃣ 很多楼没有四楼：四听起来像死。而八听起来像发。"},
    {"ru": "🍵 Слово «чай» в разных языках пришло из разных диалектов: «tea» — из миньнаньского té, «чай» — из мандаринского chá. Всё зависело от того, по морю везли или по суше.",
     "uz": "🍵 Turli tillardagi «choy» so'zi turli lahjalardan: «tea» — té, «choy» — chá.",
     "en": "🍵 'Tea' comes from Min Nan té, 'chai' from Mandarin chá — depending on sea or land trade routes.",
     "zh": "🍵 各语言中的「茶」来自不同方言：tea源于闽南语té，chai源于普通话chá。"},
    {"ru": "🐉 龙 в Китае — не злой ящер, а символ удачи и власти. Китайцы называют себя 龙的传人 — потомками дракона.",
     "uz": "🐉 龙 Xitoyda yovuz emas — omad va hokimiyat ramzi. Xitoyliklar o'zini «ajdaho avlodi» deb ataydi.",
     "en": "🐉 龙 in China is not an evil beast but a symbol of luck and power. Chinese call themselves 龙的传人.",
     "zh": "🐉 龙在中国是好运和权力的象征，中国人自称龙的传人。"},
    {"ru": "🍜 Китайцы часто здороваются фразой 吃了吗 — «ты поел?». За ней стоят голодные годы в истории страны: спросить про еду значило спросить, всё ли у человека в порядке.",
     "uz": "🍜 Xitoyliklar ko'pincha 吃了吗 — «ovqatlandingmi?» deb salomlashadi.",
     "en": "🍜 A common Chinese greeting is 吃了吗 — 'have you eaten?' It comes from times of famine.",
     "zh": "🍜 中国人常用「吃了吗」问候，这源于历史上的饥荒年代。"},
]

DICT = {
    "привет": {"zh": "你好", "py": "nǐ hǎo"},
    "спасибо": {"zh": "谢谢", "py": "xiè xie"},
    "пожалуйста": {"zh": "不客气", "py": "bú kè qi"},
    "любовь": {"zh": "爱", "py": "ài"},
    "друг": {"zh": "朋友", "py": "péng yǒu"},
    "учиться": {"zh": "学习", "py": "xué xí"},
    "мечта": {"zh": "梦想", "py": "mèng xiǎng"},
    "книга": {"zh": "书", "py": "shū"},
    "вода": {"zh": "水", "py": "shuǐ"},
    "hello": {"zh": "你好", "py": "nǐ hǎo"},
    "thanks": {"zh": "谢谢", "py": "xiè xie"},
    "love": {"zh": "爱", "py": "ài"},
    "salom": {"zh": "你好", "py": "nǐ hǎo"},
    "rahmat": {"zh": "谢谢", "py": "xiè xie"},
    "你好": {"ru": "Привет", "uz": "Salom", "en": "Hello", "py": "nǐ hǎo"},
    "谢谢": {"ru": "Спасибо", "uz": "Rahmat", "en": "Thank you", "py": "xiè xie"},
    "爱": {"ru": "Любовь", "uz": "Muhabbat", "en": "Love", "py": "ài"},
    "朋友": {"ru": "Друг", "uz": "Do'st", "en": "Friend", "py": "péng yǒu"},
    "加油": {"ru": "Давай, не сдавайся", "uz": "Harakat qil", "en": "Go for it", "py": "jiā yóu"},
    "学习": {"ru": "Учиться", "uz": "O'qimoq", "en": "To study", "py": "xué xí"},
}
