# -*- coding: utf-8 -*-
"""Переводы uz / en для главы 1 (ru лежит в ch1_src.py).
Порядок строк строго совпадает с ch1_src.SCENES. {name} = ник героя."""

CHAPTER = {
    "title": {"uz": "1-bob. Buyuk Xitoy devori sari", "en": "Chapter 1. To the Great Wall"},
    "city": {"uz": "Pekin", "en": "Beijing"},
    "goal": {"uz": "Buyuk Xitoy devoriga yetib borish", "en": "Reach the Great Wall"},
    "next": {"uz": "Keyingi maqsad: Sian, keyin Chengdu (pandalarni boqish)",
             "en": "Next goal: Xi'an, then Chengdu (feed the pandas)"},
}

CAST = {
    "me": ("Sen (qahramon)", "You (the hero)"),
    "cc": ("Chacha, choy ruhi, yo'lboshchi", "Chacha, the tea spirit and guide"),
    "li": ("Aeroport xodimasi", "Airport officer"),
    "wang": ("Taksi haydovchisi", "Taxi driver"),
    "lin": ("Mehmonxona administratori", "Hotel receptionist"),
    "zhang": ("Ovqatxona egasi", "Snack shop owner"),
    "dm": ("Pekinlik talaba, yo'ldosh", "Student from Beijing, travel buddy"),
    "staff": ("Metro xodimi", "Metro staff"),
    "ticket": ("Kassir", "Ticket seller"),
    "vend": ("Suv sotuvchi", "Water seller"),
    "old": ("Devor qorovuli, chol", "Old keeper of the Wall"),
}

# для каждой сцены: title, bg, obstacle, culture — (uz, en); dialogue — [(uz, en)];
# hints — od-подсказки [(uz,en)] по порядку od-заданий; tr — списки вариантов [(uz[4], en[4])]
SC = {
"s1": {
 "title": ("Poytaxt aeroporti", "Capital Airport"),
 "bg": ("Kelish zali, tong", "Arrivals hall, morning"),
 "obstacle": ("Pasport nazorati: o'tish uchun savollarga javob ber", "Passport control: answer the questions to get through"),
 "culture": ("«你叫什么名字？» — «isming nima?» degan oddiy savol. Juda odobli so'rash uchun: «您贵姓？» (Nín guìxìng?).",
             "“你叫什么名字？” is the everyday way to ask “What's your name?”. A very polite way is “您贵姓？” (Nín guìxìng?)."),
 "dialogue": [
  ("Xitoyga xush kelibsan! Men Chachaman. Isming nima?", "Welcome to China! I'm Chacha. What's your name?"),
  ("Mening ismim {name}.", "My name is {name}."),
  ("Salom! Pekinga xush kelibsiz! Siz talabamisiz?", "Hello! Welcome to Beijing! Are you a student?"),
  ("Ha, men talabaman.", "Yes, I'm a student."),
  ("Iltimos, pasportingizni bering.", "Please give me your passport."),
  ("Yaxshi, muammo yo'q. Xitoyda nima qilmoqchisiz?", "Okay, no problem. What will you do in China?"),
  ("Men sayohatga keldim.", "I came to travel."),
  ("Biz Buyuk Xitoy devoriga boramiz!", "We're going to the Great Wall!"),
  ("Buyuk devor uzoqda, avval mehmonxonada dam oling.", "The Great Wall is far away, so rest at the hotel first."),
 ],
 "hints": [("Men Pekinga sayohat qilgani keldim.", "I came to Beijing to travel.")],
 "tr": [(["Pekinga xush kelibsiz!", "Xayr, Pekin!", "Men Pekinni yaxshi ko'raman!", "Pekin qayerda?"],
         ["Welcome to Beijing!", "Goodbye, Beijing!", "I love Beijing!", "Where is Beijing?"])],
},
"s2": {
 "title": ("Taksi", "Taxi"),
 "bg": ("Aeroport chiqishida, sariq taksi", "Outside the airport, a yellow taxi"),
 "obstacle": ("Yo'lda tirbandlik: haydovchi bilan hisob-kitob qil", "Traffic jam: pay the driver"),
 "culture": ("师傅 (shīfu) — haydovchilar va ustalarga hurmat bilan murojaat. Pulni turlicha atashadi: og'zaki nutqda ko'proq «块» (kuài), yozuvda «元» (yuán).",
             "师傅 (shīfu) is a respectful way to address drivers and skilled workers. Money has different names: in speech usually “块” (kuài), in writing “元” (yuán)."),
 "dialogue": [
  ("Salom! Qayerga boramiz?", "Hello! Where are you headed?"),
  ("Biz «Qingcha» mehmonxonasiga boramiz.", "We're going to the Qingcha Hotel."),
  ("Xo'p, o'tiring.", "Okay, please get in."),
  ("Bugun odam ko'p, yo'lda biroz tirbandlik.", "There are lots of people today, and the road is a bit jammed."),
  ("«Duche» nima degani?", "What does “dǔchē” mean?"),
  ("Mashina juda ko'p bo'lib, juda sekin yurish.", "It's when there are too many cars and you move very slowly."),
  ("Yetib keldik! Hammasi bo'lib 120 yuan.", "We're here! 120 yuan in total."),
  ("Mana pul. Rahmat!", "Here's the money. Thank you!"),
  ("Arzimaydi! Yaxshi dam oling!", "You're welcome! Have a great time!"),
 ],
 "hints": [],
 "tr": [(["Hammasi bo'lib 120 yuan.", "Hammasi bo'lib 12 yuan.", "Hammasi bo'lib 210 yuan.", "Hammasi bo'lib 102 yuan."],
         ["120 yuan in total.", "12 yuan in total.", "210 yuan in total.", "102 yuan in total."])],
},
"s3": {
 "title": ("Mehmonxona", "Hotel"),
 "bg": ("Mehmonxona holli, qizil fonuslar", "Hotel lobby, red lanterns"),
 "obstacle": ("Kalit-karta: xona raqami va nonushta vaqtini bil", "Key card: find out your room number and breakfast time"),
 "culture": ("Xona va qavat raqamlari raqamma-raqam o'qiladi: 306 — sān líng liù (三零六). Nol — 零 (líng).",
             "Room and floor numbers are read digit by digit: 306 is sān líng liù (三零六). Zero is 零 (líng)."),
 "dialogue": [
  ("Xush kelibsiz! Bron qilganmisiz?", "Welcome! Do you have a reservation?"),
  ("Ha, mening ismim {name}.", "Yes, my name is {name}."),
  ("Yaxshi. Xonangiz — 306.", "Good. Your room is 306."),
  ("Lift anavi yerda.", "The elevator is over there."),
  ("Nonushta ertalab soat yettidan to'qqizgacha.", "Breakfast is from seven to nine in the morning."),
  ("Ertaga soat nechada yo'lga chiqamiz?", "What time do we set off tomorrow?"),
  ("Ertalab soat sakkizda! Biz Buyuk devorga boramiz.", "At eight in the morning! We're going to the Great Wall."),
  ("Buyuk devorgami? Barvaqtroq yotib oling!", "To the Great Wall? Go to bed early!"),
  ("Xo'p, xayrli tun!", "Okay, good night!"),
 ],
 "hints": [("Biz ertaga ertalab soat sakkizda yo'lga chiqamiz.", "We set off tomorrow at 8 in the morning.")],
 "tr": [],
},
"s4": {
 "title": ("Ovqatxonada nonushta", "Breakfast at the snack shop"),
 "bg": ("Ko'cha ovqatxonasi, savatlar ustida bug'", "Street eatery, steam rising from the baskets"),
 "obstacle": ("Achchiq qalampir: ovqat buyurtma ber va sendan nima so'ralayotganini tushun",
              "Spicy chili: order food and understand what you're being asked"),
 "culture": ("Xitoyda nonushtaga ko'pincha baozi, lag'mon, soya suti iste'mol qilinadi. «我不吃辣» — «achchiq yemayman» — achchiq yoqmasa eng kerakli ibora: Sichuanda juda achchiq.",
             "For breakfast, people in China often eat baozi, noodles and soy milk. “我不吃辣” (“I don't eat spicy food”) is the most useful phrase if you don't like heat: Sichuan food is very spicy."),
 "dialogue": [
  ("Xayrli tong! Nima yeysizlar?", "Good morning! What would you like to eat?"),
  ("Bizda baozi, chuchvara va lag'mon bor.", "We have baozi, dumplings and noodles."),
  ("Men baozi yemoqchiman.", "I'd like baozi."),
  ("Menga bir kosa lag'mon va bir piyola choy.", "I'll have a bowl of noodles and a cup of tea."),
  ("Achchiq ovqat yeysanmi?", "Do you eat spicy food?"),
  ("Men achchiq yemayman.", "I don't eat spicy food."),
  ("Salom! Mening ismim Daming, Pekin universiteti talabasiman.", "Hi! My name is Daming, I'm a student at Peking University."),
  ("Qayerga ketyapsizlar?", "Where are you headed?"),
  ("Biz Buyuk devorga bormoqchimiz.", "We want to go to the Great Wall."),
  ("Juda yaxshi! Men ham bormoqchiman, sizlarni olib borishim mumkin.", "Great! I want to go too, I can take you there."),
  ("Hammasi bo'lib 28 yuan.", "28 yuan in total."),
 ],
 "hints": [("Menga bir kosa lag'mon.", "One bowl of noodles for me.")],
 "tr": [(["Men ham bormoqchiman.", "Men bormoqchi emasman.", "U ham bormoqchi.", "Men allaqachon borganman."],
         ["I want to go too.", "I don't want to go.", "He wants to go too.", "I've already been."])],
},
"s5": {
 "title": ("Metro", "Metro"),
 "bg": ("Metro platformasi, olomon", "Metro platform, a crowd"),
 "obstacle": ("Metrodagi olomon: kerakli liniyani top va Chachani yo'qotma", "Metro crowd: find the right line and don't lose Chacha"),
 "culture": ("Metro liniyalari raqami bilan ataladi: 二号线 (èr hào xiàn) — «2-liniya». 西直门 (Xīzhímén) — Shimoliy vokzal yaqinidagi o'tish tuguni. «请排队» (qǐng páiduì) — «navbatga turing», platformalardagi ibora.",
             "Metro lines are called by number: 二号线 (èr hào xiàn) means “Line 2”. Xizhimen (西直门) is a transfer hub near the North Station. “请排队” (qǐng páiduì), “please line up”, is a platform phrase."),
 "dialogue": [
  ("Avval metroda Xizhimenga boramiz.", "First, let's take the metro to Xizhimen."),
  ("Metro bekati qayerda?", "Where is the metro station?"),
  ("Aynan oldinda. To'g'ri yuring, keyin o'ngga buriling.", "Right ahead. Go straight, then turn right."),
  ("Nechanchi liniyada ketamiz?", "Which line do we take?"),
  ("2-liniyada Xizhimen bekatigacha boramiz. Keyin Pekin Shimoliy vokzaligacha piyoda boramiz.", "We take Line 2 to Xizhimen station, then walk to Beijing North Station."),
  ("Navbatga turing! Keyingi bekat — Xizhimen.", "Please line up! The next station is Xizhimen."),
  ("Odam naqadar ko'p!", "So many people!"),
  ("Xavotir olma, shoshmasdan yuramiz.", "Don't worry, we'll walk without rushing."),
 ],
 "hints": [("Avval biz 2-liniyada ketamiz.", "First we'll take Line 2.")],
 "tr": [],
},
"s6": {
 "title": ("Shimoliy vokzal va chiptalar", "North Station and tickets"),
 "bg": ("Shimoliy vokzal, tablo, kassa darchasi", "North Station, departure board, ticket window"),
 "obstacle": ("Soat 8 dagi chiptalar sotilib bo'lgan: boshqasini ol va ob-havoni bil", "The 8 o'clock tickets are sold out: buy others and ask about the weather"),
 "culture": ("Xitoyda poyezd chiptalari pasport bo'yicha olinadi. Tezyurar poyezd Shimoliy vokzaldan Devor ostidagi bekatgacha taxminan 20 daqiqa yuradi. «天气» (tiānqì) — ob-havo: 晴天 (ochiq), 阴天 (bulutli), 下雨 (yomg'ir yog'yapti), 下雪 (qor yog'yapti).",
             "Train tickets in China are bought with a passport. The high-speed train takes about 20 minutes from the North Station to the stop right under the Wall. And “天气” (tiānqì) is the weather: 晴天 (sunny), 阴天 (cloudy), 下雨 (raining), 下雪 (snowing)."),
 "dialogue": [
  ("Salom, chipta olasizlarmi?", "Hello, would you like to buy tickets?"),
  ("Biz «Badaling Buyuk devor» bekatiga uchta chipta olmoqchimiz.", "We'd like three tickets to Badaling Great Wall station."),
  ("Ertaga ertalab soat 8 dagi chiptalar sotilib bo'lgan, soat 9 dagisi bor.", "Tomorrow's 8 a.m. tickets are sold out; there are 9 o'clock ones."),
  ("Yaxshi, 9 dagisini olamiz.", "Okay, we'll take the 9 o'clock."),
  ("Uchta, hammasi bo'lib 90 yuan.", "Three tickets, 90 yuan in total."),
  ("Tezyurar poyezd juda tez, atigi yigirma daqiqa.", "The high-speed train is very fast, only twenty minutes."),
  ("Ertaga ob-havo qanday bo'ladi?", "What will the weather be like tomorrow?"),
  ("Eshitishimcha, ertaga ochiq, yomg'ir yog'maydi.", "I hear tomorrow will be sunny, with no rain."),
  ("Juda yaxshi! Men eng ko'p ochiq havoni yaxshi ko'raman.", "Great! I like sunny weather the most."),
 ],
 "hints": [("Bizga soat 9 dagi chiptalar kerak.", "We need the 9 o'clock tickets.")],
 "tr": [(["Chiptalar sotilib bo'lgan.", "Chiptalar qimmat.", "Men chipta sotib oldim.", "Chiptalar hali bor."],
         ["The tickets are sold out.", "The tickets are expensive.", "I bought a ticket.", "There are still tickets."])],
},
"s7": {
 "title": ("Devor etagida", "At the foot of the Wall"),
 "bg": ("Tog' etagi, tepaga ko'tarilgan zinapoyalar, peshtaxtalar", "Foot of the mountain, steps leading up, stalls"),
 "obstacle": ("Tik ko'tarilish: suv kerak, sotuvchi esa qimmat so'rayapti", "Steep climb: you need water, but the seller asks too much"),
 "culture": ("Turistik joylarda savdolashish mumkin. «便宜一点儿吧» (piányi yìdiǎnr ba) — «biroz arzonroq qiling» — bozordagi eng foydali ibora.",
             "At tourist sites you can bargain. “便宜一点儿吧” (piányi yìdiǎnr ba), “make it a bit cheaper”, is the most useful market phrase."),
 "dialogue": [
  ("Suv! Suv! Suv kerakmi? Bir shisha — 5 yuan!", "Water! Water! Want some water? 5 yuan a bottle!"),
  ("Juda qimmat! Biroz arzonroq qiling.", "Too expensive! Make it a bit cheaper."),
  ("Xo'p, to'rt yuan.", "Fine, four yuan."),
  ("Yaxshi, ikki shisha olaman.", "Okay, I'll take two bottles."),
  ("Devorda zinapoyalar ko'p. Shoshmasdan ko'tarilamiz.", "There are many steps on the Wall. We'll climb without rushing."),
  ("Men biroz charchadim.", "I'm a little tired."),
  ("Dadil bo'l! Tez orada yetamiz!", "Hang in there! We're almost there!"),
  ("Qara, anavi — Buyuk devor!", "Look, that's the Great Wall!"),
 ],
 "hints": [("Biroz arzonroq qiling.", "Make it a bit cheaper.")],
 "tr": [],
},
"s8": {
 "title": ("Buyuk Xitoy devori", "The Great Wall"),
 "bg": ("Tong otayotgan Buyuk devor, qorovul minoralari", "The Great Wall at dawn, watchtowers"),
 "obstacle": ("Bobning finali: devor qorovuliga javob ber va esdalik surati ol", "Chapter finale: answer the Wall's keeper and get a souvenir photo"),
 "culture": ("«不到长城非好汉» (Bú dào Chángchéng fēi hǎohàn) — mashhur satr: «Buyuk devorga chiqmagan — qahramon emas».",
             "“不到长城非好汉” (Bú dào Chángchéng fēi hǎohàn) is a famous line: “He who has not climbed the Great Wall is not a true hero.”"),
 "dialogue": [
  ("Yoshlar, salom! Qayerdan kelyapsizlar?", "Young people, hello! Where are you from?"),
  ("Biz uzoq joydan keldik.", "We came from far away."),
  ("Buyuk devorga chiqmagan — qahramon emas! Siz bu yerga ko'tarildingiz, ofarin!", "He who hasn't climbed the Great Wall is no hero! You made it up here, well done!"),
  ("Vov, Buyuk devor naqadar uzun!", "Wow, the Great Wall is so long!"),
  ("Sizlarni suratga olib beraman.", "Let me take a photo of you."),
  ("Jilmaying!", "Smile!"),
  ("Keyingi bekat — Sian! U yerda terakota armiyasi va mazali chuchvaralar bor.", "Next stop: Xi'an! There's the Terracotta Army and tasty dumplings."),
  ("Keyin Chengduga pandalarni ko'rgani boramiz!", "And then to Chengdu to see pandas!"),
  ("Ajoyib! Yo'lga chiqdik!", "Awesome! Let's go!"),
 ],
 "hints": [("Buyuk devorga chiqmagan — qahramon emas.", "Whoever hasn't climbed the Great Wall is no hero.")],
 "tr": [(["Sizlarni suratga olib beraman.", "Menga surat bering.", "Siz otkritka sotib oldingiz.", "Men suratga tushishni yoqtirmayman."],
         ["Let me take a photo of you.", "Give me the photo.", "You bought a postcard.", "I don't like having my picture taken."])],
},
}
